set_property SRC_FILE_INFO {cfile:/afs/athena.mit.edu/user/m/a/magson/6111/6111work/Project/baseline_test/baseline_test/baseline_test.runs/synth_1/.Xil/Vivado-4449-eecs-digital-18/dcp/one_image_48_48_in_context.xdc rfile:../dcp/one_image_48_48_in_context.xdc id:1 order:EARLY scoped_inst:dg1/rom_1} [current_design]
set_property SRC_FILE_INFO {cfile:/afs/athena.mit.edu/user/m/a/magson/6111/6111work/Project/baseline_test/baseline_test/baseline_test.runs/synth_1/.Xil/Vivado-4449-eecs-digital-18/dcp_2/two_image_48_48_in_context.xdc rfile:../dcp_2/two_image_48_48_in_context.xdc id:2 order:EARLY scoped_inst:dg1/rom_2} [current_design]
set_property SRC_FILE_INFO {cfile:/afs/athena.mit.edu/user/m/a/magson/6111/6111work/Project/baseline_test/baseline_test/baseline_test.runs/synth_1/.Xil/Vivado-4449-eecs-digital-18/dcp_3/three_image_48_48_in_context.xdc rfile:../dcp_3/three_image_48_48_in_context.xdc id:3 order:EARLY scoped_inst:dg1/rom_3} [current_design]
set_property SRC_FILE_INFO {cfile:/afs/athena.mit.edu/user/m/a/magson/6111/6111work/Project/baseline_test/baseline_test/baseline_test.runs/synth_1/.Xil/Vivado-4449-eecs-digital-18/dcp_4/four_image_48_48_in_context.xdc rfile:../dcp_4/four_image_48_48_in_context.xdc id:4 order:EARLY scoped_inst:dg1/rom_4} [current_design]
set_property SRC_FILE_INFO {cfile:/afs/athena.mit.edu/user/m/a/magson/6111/6111work/Project/baseline_test/baseline_test/baseline_test.runs/synth_1/.Xil/Vivado-4449-eecs-digital-18/dcp_5/five_image_48_48_in_context.xdc rfile:../dcp_5/five_image_48_48_in_context.xdc id:5 order:EARLY scoped_inst:dg1/rom_5} [current_design]
set_property SRC_FILE_INFO {cfile:/afs/athena.mit.edu/user/m/a/magson/6111/6111work/Project/baseline_test/baseline_test/baseline_test.runs/synth_1/.Xil/Vivado-4449-eecs-digital-18/dcp_6/six_image_48_48_in_context.xdc rfile:../dcp_6/six_image_48_48_in_context.xdc id:6 order:EARLY scoped_inst:dg1/rom_6} [current_design]
set_property SRC_FILE_INFO {cfile:/afs/athena.mit.edu/user/m/a/magson/6111/6111work/Project/baseline_test/baseline_test/baseline_test.runs/synth_1/.Xil/Vivado-4449-eecs-digital-18/dcp_7/seven_image_48_48_in_context.xdc rfile:../dcp_7/seven_image_48_48_in_context.xdc id:7 order:EARLY scoped_inst:dg1/rom_7} [current_design]
set_property SRC_FILE_INFO {cfile:/afs/athena.mit.edu/user/m/a/magson/6111/6111work/Project/baseline_test/baseline_test/baseline_test.runs/synth_1/.Xil/Vivado-4449-eecs-digital-18/dcp_8/eight_image_48_48_in_context.xdc rfile:../dcp_8/eight_image_48_48_in_context.xdc id:8 order:EARLY scoped_inst:dg1/rom_8} [current_design]
set_property SRC_FILE_INFO {cfile:/afs/athena.mit.edu/user/m/a/magson/6111/6111work/Project/baseline_test/baseline_test/baseline_test.runs/synth_1/.Xil/Vivado-4449-eecs-digital-18/dcp_9/nine_image_48_48_in_context.xdc rfile:../dcp_9/nine_image_48_48_in_context.xdc id:9 order:EARLY scoped_inst:dg1/rom_9} [current_design]
set_property SRC_FILE_INFO {cfile:/afs/athena.mit.edu/user/m/a/magson/6111/6111work/Project/baseline_test/baseline_test/baseline_test.runs/synth_1/.Xil/Vivado-4449-eecs-digital-18/dcp_10/clk_wiz_0_in_context.xdc rfile:../dcp_10/clk_wiz_0_in_context.xdc id:10 order:EARLY scoped_inst:clkdivider} [current_design]
set_property SRC_FILE_INFO {cfile:/afs/athena.mit.edu/user/m/a/magson/6111/6111work/Project/baseline_test/baseline_test/baseline_test.srcs/constrs_1/imports/baseline_test/Nexys4DDR_Master_lab5c.xdc rfile:../../../../../baseline_test.srcs/constrs_1/imports/baseline_test/Nexys4DDR_Master_lab5c.xdc id:11} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins dg1/rom_1/clka]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells dg1/rom_1]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins dg1/rom_2/clka]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells dg1/rom_2]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins dg1/rom_3/clka]
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells dg1/rom_3]
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins dg1/rom_4/clka]
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells dg1/rom_4]
set_property src_info {type:SCOPED_XDC file:5 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins dg1/rom_5/clka]
set_property src_info {type:SCOPED_XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells dg1/rom_5]
set_property src_info {type:SCOPED_XDC file:6 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins dg1/rom_6/clka]
set_property src_info {type:SCOPED_XDC file:6 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells dg1/rom_6]
set_property src_info {type:SCOPED_XDC file:7 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins dg1/rom_7/clka]
set_property src_info {type:SCOPED_XDC file:7 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells dg1/rom_7]
set_property src_info {type:SCOPED_XDC file:8 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins dg1/rom_8/clka]
set_property src_info {type:SCOPED_XDC file:8 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells dg1/rom_8]
set_property src_info {type:SCOPED_XDC file:9 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins dg1/rom_9/clka]
set_property src_info {type:SCOPED_XDC file:9 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells dg1/rom_9]
set_property src_info {type:SCOPED_XDC file:10 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports CLK100MHZ]
set_property src_info {type:SCOPED_XDC file:10 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports CLK100MHZ]
set_property src_info {type:SCOPED_XDC file:10 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells clkdivider]
set_property src_info {type:SCOPED_XDC file:10 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name CLK100MHZ [get_ports CLK100MHZ]
set_property src_info {type:SCOPED_XDC file:10 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports CLK100MHZ] -edges {1 2 3} -edge_shift {0.000 15.000 30.000} [get_pins clkdivider/clk_out1]
set_property src_info {type:XDC file:11 line:8 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports CLK100MHZ]
