# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /afs/athena.mit.edu/user/m/a/magson/6111/6111work/Project/baseline_test/baseline_test/baseline_test.cache/wt [current_project]
set_property parent.project_path /afs/athena.mit.edu/user/m/a/magson/6111/6111work/Project/baseline_test/baseline_test/baseline_test.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
add_files /afs/athena.mit.edu/user/m/a/magson/6111/6111work/Project/baseline_test/one.coe
add_files /afs/athena.mit.edu/user/m/a/magson/6111/6111work/Project/baseline_test/two.coe
add_files /afs/athena.mit.edu/user/m/a/magson/6111/6111work/Project/baseline_test/three.coe
add_files /afs/athena.mit.edu/user/m/a/magson/6111/6111work/Project/baseline_test/four.coe
add_files /afs/athena.mit.edu/user/m/a/magson/6111/6111work/Project/baseline_test/five.coe
add_files /afs/athena.mit.edu/user/m/a/magson/6111/6111work/Project/baseline_test/six.coe
add_files /afs/athena.mit.edu/user/m/a/magson/6111/6111work/Project/baseline_test/seven.coe
add_files /afs/athena.mit.edu/user/m/a/magson/6111/6111work/Project/baseline_test/eight.coe
add_files /afs/athena.mit.edu/user/m/a/magson/6111/6111work/Project/baseline_test/nine.coe
read_verilog -library xil_defaultlib {
  /afs/athena.mit.edu/user/m/a/magson/6111/6111work/Project/baseline_test/baseline_test/baseline_test.srcs/sources_1/imports/baseline_test/xvga.v
  /afs/athena.mit.edu/user/m/a/magson/6111/6111work/Project/baseline_test/baseline_test/baseline_test.srcs/sources_1/imports/baseline_test/clk_wiz_0_clk_wiz.v
  /afs/athena.mit.edu/user/m/a/magson/6111/6111work/Project/baseline_test/baseline_test/baseline_test.srcs/sources_1/imports/baseline_test/display_8hex.v
  /afs/athena.mit.edu/user/m/a/magson/6111/6111work/Project/baseline_test/baseline_test/baseline_test.srcs/sources_1/imports/baseline_test/base.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /afs/athena.mit.edu/user/m/a/magson/6111/6111work/Project/baseline_test/baseline_test/baseline_test.srcs/constrs_1/imports/baseline_test/Nexys4DDR_Master_lab5c.xdc
set_property used_in_implementation false [get_files /afs/athena.mit.edu/user/m/a/magson/6111/6111work/Project/baseline_test/baseline_test/baseline_test.srcs/constrs_1/imports/baseline_test/Nexys4DDR_Master_lab5c.xdc]


synth_design -top labkit -part xc7a100tcsg324-1


write_checkpoint -force -noxdef labkit.dcp

catch { report_utilization -file labkit_utilization_synth.rpt -pb labkit_utilization_synth.pb }
