# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /afs/athena.mit.edu/user/s/h/shreeyam/Documents/6.111/6111/6111work/Project/sudoku/sudoku.srcs/sources_1/ip/rescaled_frame_buffer/rescaled_frame_buffer.xci
# IP: The module: 'rescaled_frame_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /afs/athena.mit.edu/user/s/h/shreeyam/Documents/6.111/6111/6111work/Project/sudoku/sudoku.srcs/sources_1/ip/rescaled_frame_buffer/rescaled_frame_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rescaled_frame_buffer'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /afs/athena.mit.edu/user/s/h/shreeyam/Documents/6.111/6111/6111work/Project/sudoku/sudoku.srcs/sources_1/ip/rescaled_frame_buffer/rescaled_frame_buffer.xci
# IP: The module: 'rescaled_frame_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /afs/athena.mit.edu/user/s/h/shreeyam/Documents/6.111/6111/6111work/Project/sudoku/sudoku.srcs/sources_1/ip/rescaled_frame_buffer/rescaled_frame_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rescaled_frame_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
