# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /afs/athena.mit.edu/user/s/h/shreeyam/Documents/6.111/6111/6111work/Project/baseline_test/baseline_test/baseline_test.srcs/sources_1/ip/four_image_48_48/four_image_48_48.xci
# IP: The module: 'four_image_48_48' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /afs/athena.mit.edu/user/s/h/shreeyam/Documents/6.111/6111/6111work/Project/baseline_test/baseline_test/baseline_test.srcs/sources_1/ip/four_image_48_48/four_image_48_48_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'four_image_48_48'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /afs/athena.mit.edu/user/s/h/shreeyam/Documents/6.111/6111/6111work/Project/baseline_test/baseline_test/baseline_test.srcs/sources_1/ip/four_image_48_48/four_image_48_48.xci
# IP: The module: 'four_image_48_48' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /afs/athena.mit.edu/user/s/h/shreeyam/Documents/6.111/6111/6111work/Project/baseline_test/baseline_test/baseline_test.srcs/sources_1/ip/four_image_48_48/four_image_48_48_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'four_image_48_48'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
